### ISSUE TITLE
RFE: RHV import / conversion pod names not as user-friendly as VMware

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-controller#398]
https://github.com/konveyor/forklift-must-gather/blob/af0bf5f53c5937077e94a5bc28f84809e497f359/README.md?plain=1#L87

This line is an example of a VMware importer pod name. RHV importer and conversion pods, however, have names that look like this: `importer-<plan>-ed90dfc6-9a17-4a8btnfh`, where `ed90dfc6-9a17-4a8` is the beginning of the RHV VM ID and `btnfh` is an ID.

It would be more user-friendly if the VM name could be used instead. If this is not possible, perhaps include `-vm-` in the name before the ID and a hyphen between the VM ID and 5-char ID:  `importer-<plan>-vm-ed90dfc6-9a17-4a8-btnfh`.

**Comment by mansam** [comment]
The importers are all named in the format `importer-<datavolume name>`, where `<datavolume name>` is in the format `<planname>-<vmid>-<generated>`. Similarly the conversion pods are all named in the format `<planname>-<vmid>-<generated>`. These names are generated the same way for all providers, and the reason `vm` shows up in the name of the vSphere pods is because `vm-` is part of the ID. We do not use the VM name because it could be arbitrarily long.

You are seeing pods for RHV VMs with names like `importer-<plan>-ed90dfc6-9a17-4a8btnfh` because the plan name is excessively long, and Kubernetes is having to truncate the pod name in order to apply the generated tag. You would see the same for vSphere VMs belonging to plans with excessively long names. If the plan name was shorter you would see that there is a hyphen before the generated tag, but because the plan name is so long it is lost.

**Comment by apinnick** [comment]
Closing this bug because there does not seem to be any way to make pod names more user-friendly. The structure of the must-gather archive is probably sufficient for the user to figure out the pods.
